# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 10:55
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='date created')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'verbose_name': 'Category',
                'default_related_name': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Score')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='date created')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to=settings.AUTH_USER_MODEL, verbose_name='Provider')),
            ],
            options={
                'verbose_name_plural': 'Evaluations',
                'verbose_name': 'Evaluation',
                'default_related_name': 'evaluations',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='date created')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL, verbose_name='Provider')),
            ],
            options={
                'verbose_name_plural': 'Location',
                'verbose_name': 'Locations',
                'default_related_name': 'locations',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='Phone')),
                ('role', models.PositiveIntegerField(blank=True, choices=[(1, 'Administrador'), (2, 'Cliente'), (3, 'Proveedor')], null=True, verbose_name='Role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profile',
                'verbose_name': 'Profile',
                'default_related_name': 'profile',
            },
        ),
        migrations.CreateModel(
            name='ProviderService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_services', to=settings.AUTH_USER_MODEL, verbose_name='Provider')),
            ],
            options={
                'verbose_name_plural': 'Provider Services',
                'verbose_name': 'Provider Service',
                'default_related_name': 'provider_services',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Time')),
                ('date', models.DateField(verbose_name='Date')),
                ('status', models.PositiveIntegerField(blank=True, choices=[(1, 'Asignada'), (2, 'Cancelada'), (3, 'Pendiente'), (4, 'No Realizada'), (5, 'Realizada')], verbose_name='Status')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_reservations', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_reservations', to=settings.AUTH_USER_MODEL, verbose_name='Provider')),
            ],
            options={
                'verbose_name_plural': 'Reservations',
                'verbose_name': 'Reservation',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='date created')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='backend.Category', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Services',
                'verbose_name': 'Service',
                'default_related_name': 'services',
            },
        ),
        migrations.AddField(
            model_name='providerservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_services', to='backend.Service', verbose_name='Service'),
        ),
    ]
