# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Cliente'), (2, 'Proveedor')], null=True, verbose_name='Role'),
        ),
    ]
